CloudBundle_homepage:
    pattern:  /
    defaults: { _controller: CloudBundle:Default:index }

CloudBundle_todo:
    pattern:  /todo
    defaults: { _controller: CloudBundle:Default:todo }

CloudBundle_features:
    pattern:  /features
    defaults: { _controller: CloudBundle:Default:features }

CloudBundle_deploy:
    pattern:  /apps/{name}
    defaults: { _controller: CloudBundle:Deploy:deploy }
    requirements:
        _method:  POST

CloudBundle_manage:
    pattern:  /manage
    defaults: { _controller: CloudBundle:Manage:index }

CloudBundle_new_app:
    pattern:  /manage/apps/new
    defaults: { _controller: CloudBundle:Manage:new }

CloudBundle_view_app:
    pattern:  /manage/apps/{name}
    defaults: { _controller: CloudBundle:Manage:view }

CloudBundle_deploy_script:
    pattern:  /manage/apps/{name}/deploy
    defaults: { _controller: CloudBundle:Manage:deployScript }

CloudBundle_delete_app:
    pattern:  /manage/apps/{name}/delete
    defaults: { _controller: CloudBundle:Manage:delete }